#!/usr/bin/env python

import argparse
import os
import sys
import textwrap
import time

import numpy as np
import progressbar

from hexrd.coreutil import initialize_experiment, merge_dicts


def migrate_detector_parameters(old, new, rows, cols, size):
    pass


def extract_measured_g_vectors(
    cfg, pd, reader, detector, verbose=False, force=False
    ):

    #####################
    ## load parameters ##
    #####################

    cwd = cfg.get('working_dir', os.getcwd())
    analysis_root = os.path.join(cwd, cfg['analysis_name'])

    exgcfg = cfg['extract_measured_g_vectors']
    pthresh = exgcfg['threshold']
    tth_max = exgcfg.get('tth_max', True)
    try:
        tth_tol = exgcfg['tolerance'].get('tth', None)
        eta_tol = exgcfg['tolerance'].get('eta', None)
        ome_tol = exgcfg['tolerance'].get('ome', None)
    except KeyError:
        tth_tol = eta_tol = ome_tol = None
    if tth_tol is None:
        tth_tol = 0.2
    if eta_tol is None:
        eta_tol = 1
    if ome_tol is None:
        ome_tol = 2*cfg['image_series']['ome']['step']

    ###########################
    ## Instrument parameters ##
    ###########################

    # attempt to load the new detector parameter file
    det_p = os.path.join(analysis_root, cfg['detector']['parameters'])
    if not os.path.exists(det_p):
        det_o = os.path.join(analysis_root, cfg['detector']['parameters_old'])
        rows = cfg['detector']['pixels']['rows']
        cols = cfg['detector']['pixels']['cols']
        psize = cfg['detector']['pixels']['size']
        migrate_detector_parameters(det_o, det_p, rows, cols, psize)

    geomParams = np.vstack(
        [detector.getParams(allParams=True)[:6],
        np.zeros(6)]
        ).T

    distortion = (dFuncs.GE_41RT, detector.getParams(allParams=True)[6:])

    tVec_d = tVec_d_from_old_parfile(geomParams, det_origin)
    detector_params = np.hstack([geomParams[3:6, 0], tVec_d.flatten(), 0., np.zeros(3)])

    if tth_max is True:
        pd.exclusions = np.zeros_like(pd.exclusions, dtype=bool)
        pd.exclusions = pd.getTTh() > detector.getTThMax()
    elif tth_max > 0:
        pd.exclusions = np.zeros_like(pd.exclusions, dtype=bool)
        pd.exclusions = pd.getTTh() >= np.radians(tth_max)
    elif tth_max < 0:
        if verbose:
            print "Ignoring invalid tth_max: %g."
            "Must be 'true', 'false', or a non-negative value"

    phi, n = rot.angleAxisOfRotMat(rot.rotMatOfQuat(qbar))
    if have_progBar:
        widgets = [Bar('>'), ' ', ETA(), ' ', ReverseBar('<')]
        pbar = ProgressBar(widgets=widgets, maxval=len(qbar.T)).start()
        pass
    print "pulling spots for %d orientations..." %len(qbar.T)

    cwd = cfg['base'].get('working_dir', os.getcwd())
    analysis_name = cfg['base']['analysis_name']
    spots_f = os.path.join(cwd, analysis_name, 'spots_%05d.out')
    for iq, quat in enumerate(qbar.T):
        if have_progBar:
            pbar.update(iq)
        exp_map = phi[iq]*n[:, iq]
        grain_params = np.hstack([exp_map.flatten(), 0., 0., 0., 1., 1., 1., 0., 0., 0.])
        sd = xrdutil.pullSpots(
            args.pd,
            detector_params,
            grain_params,
            args.reader,
            filename=spots_f % iq,
            eta_range=etaRange,
            ome_period=ome_period,
            eta_tol=eta_tol,
            ome_tol=ome_tol,
            threshold=pthresh,
            tth_tol=tth_tol,
            distortion=distortion
            )
        pass
    if have_progBar:
        pbar.finish()
        pass
    pass # condidional on pull spots


def main(cfg, verbose=False, force=False):
    if verbose:
        print "Using '%s' configuration file" % cfg

    # need to iterate here
    # for cfg in cfgs
    with open(yml_file, 'r') as f:
        cfgs = [cfg for cfg in yaml.load_all(f)]
    cfg = cfgs[0]

    # a goofy call, could be replaced with two more targeted calls
    pd, reader, detector = initialize_experiment(cfg)

    for i, c in enumerate(cfgs):
        cfg = merge_dicts(cfg, c)
        extract_measured_g_vectors(cfg, verbose=verbose, force=force)


if __name__ == '__main__':
    parser = argparse.ArgumentParser(
        description='Extracts measured G vectors',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=textwrap.dedent('''
            example:
            $ extract_gvecs -v configuration.yml
            ''')
        )
    parser.add_argument(
        'yml', type=str,
        help='YAML configuration file'
        )
    parser.add_argument(
        '-v', '--verbose', action='store_true',
        help='report progress in terminal'
        )
    parser.add_argument(
        '-f', '--force', action='store_true',
        help='force overwrite of existing data'
        )
    main(args.yml, verbose=args.verbose, force=args.force)
