package:
  name: hexrd
  version: {{ environ.get('GIT_DESCRIBE_TAG', '')[1:] }}

source:
  #git_url: https://github.com/joelvbernier/hexrd.git
  #git_tag: v0.3.x
  git_url: ../

build:
  detect_binary_files_with_prefix: true
  osx_is_app: yes
  entry_points:
    - hexrd = hexrd.cli:main

app:
  entry: hexrd gui
  summary: High-energy x-ray diffraction analysis

requirements:
  build:
    - numba
    - numpy
    - python
    - setuptools
  run:
    - h5py
    - joblib
    - matplotlib
    - numba
    - numpy
    - progressbar >=2.3
    - python
    - python.app # [osx]
    - pyyaml
    - qtconsole
    - scikit-learn
    - scipy
    - wxpython ==3

test:
  imports:
    - hexrd
  commands:
    - hexrd -V
    - hexrd -h
    - hexrd help
    - hexrd find-orientations -h
    - hexrd help find-orientations
    - hexrd fit-grains -h
    - hexrd help fit-grains
    - hexrd gui -h
    - hexrd help gui
    - hexrd test

about:
  license: LGPL
  home: https://github.com/praxes/hexrd
  summary: High energy diffraction data analysis
