package:
  name: hexrd
  version: 0.2.1.dev

source:
  #git_url: https://github.com/praxes/hexrd.git
  #git_tag: master
  path: ../

build:
  osx_is_app: yes
  entry_points:
    - hexrd = hexrd.cli:main

app:
  entry: hexrd
  summary: High-energy x-ray diffraction analysis

requirements:
  build:
    - matplotlib
#    - numba
#    - numbapro
    - numpy
    - python
    - scipy
    - wxpython
  run:
    - matplotlib
#    - numba
#    - numbapro
    - numpy
    - progressbar
    - python
    - python.app # [osx]
    - pyyaml
    - scikit-learn
    - scipy
    - wxpython

test:
  imports:
    - hexrd
  commands:
    - hexrd -h
    - hexrd help
    - hexrd find-orientations -h
    - hexrd help find-orientations
    - hexrd fit-grains -h
    - hexrd help fit-grains
    - hexrd gui -h
    - hexrd help gui

about:
  license: LGPL
  home: https://github.com/praxes/hexrd
  summary: High energy diffraction data analysis
